############################################################################################
################################### application ############################################
############################################################################################
application:
  name: 配置中心客户端支持消息总线动态刷新版示例2-v1.1